name: Daily Checks

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get stakeholders.
      run: mkdir -p ./src/NAP.AutoChecks/data/stakeholders && wget -q -O ./src/NAP.AutoChecks/data/stakeholders/organizations.csv ${{ secrets.DROPBOX_STAKEHOLDERS }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal  

    - name: Run
      run: cd ./src/NAP.AutoChecks/ && dotnet run -c release ./data/

    - uses: deka0106/upload-to-dropbox@v2
      with:
        dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        src: ./src/NAP.AutoChecks/data/**/*
        dest: /data/
        multiple: true
        