name: Daily Checks

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get stakeholders.
      run: mkdir -p ./data/stakeholders && wget -q -O ./data/stakeholders/organisations.csv ${{ secrets.DROPBOX_STAKEHOLDERS }}

    - name: Get stakeholders.
      run: mkdir -p ./data/stakeholders && wget -q -O ./data/stakeholders/organisations_MMTIS.csv ${{ secrets.DROPBOX_STAKEHOLDERS_MMTIS }}

    - name: Get stakeholders.
      run: mkdir -p ./data/stakeholders && wget -q -O ./data/stakeholders/organizations_mmtis_categories.csv ${{ secrets.DROPBOX_STAKEHOLDERS_MMTIS_CATEGORIES }}

    - name: Get stakeholders.
      run: mkdir -p ./data/stakeholders && wget -q -O ./data/stakeholders/organisations_RTTI.csv ${{ secrets.DROPBOX_STAKEHOLDERS_RTTI }}

    - name: Get stakeholders.
      run: mkdir -p ./data/stakeholders && wget -q -O ./data/stakeholders/organisations_SRTI.csv ${{ secrets.DROPBOX_STAKEHOLDERS_SRTI }}

    - name: Get stakeholders.
      run: mkdir -p ./data/stakeholders && wget -q -O ./data/stakeholders/organisations_SSTP.csv ${{ secrets.DROPBOX_STAKEHOLDERS_SSTP }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal  

    - name: Run
      run: cd ./src/NAP.AutoChecks/ && dotnet run -c release ../../data/

    - name: Mirror Directory Structure
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        filename: ./data/**/*
        folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER }}
        overwrite: "true"
        mirrorDirectoryStructure: "true"

    - name: Upload organization results
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        filename: ./data/**/**/*
        folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER }}
        overwrite: "true"
        mirrorDirectoryStructure: "true"

    - name: Upload declarations
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        filename: ./data/**/**/*
        folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER }}
        overwrite: "true"
        mirrorDirectoryStructure: "true"



        
